{                                                      
	                                                    
	"total":28,"rows":[                                                          
		{"code":"01","name":"汉族"},         
		{"code":"02","name":"蒙古族"},         
		{"code":"03","name":"回族"},         
		{"code":"04","name":"藏族"},         
		{"code":"05","name":"维吾尔族"},         
		{"code":"06","name":"苗族"},          
		{"code":"07","name":"彝族"},          
		{"code":"08","name":"壮族"},          
		{"code":"09","name":"布依族"},          
		{"code":"10","name":"朝鲜族"},   
		{"code":"11","name":"Name 1"},         
		{"code":"12","name":"Name 2"},         
		{"code":"13","name":"Name 3"},         
		{"code":"004","name":"Name 4"},         
		{"code":"005","name":"Name 5"},         
		{"code":"006","name":"Name 6"},          
		{"code":"007","name":"Name 7"},          
		{"code":"008","name":"Name 8"},          
		{"code":"009","name":"Name 9"},          
		{"code":"010","name":"Name 10"},
		{"code":"001","name":"Name 1"},         
		{"code":"002","name":"Name 2"},         
		{"code":"003","name":"Name 3"},         
		{"code":"004","name":"Name 4"},         
		{"code":"005","name":"Name 5"},         
		{"code":"006","name":"Name 6"},          
		{"code":"007","name":"Name 7"},          
		{"code":"008","name":"Name 8"},          
		{"code":"009","name":"Name 9"},          
		{"code":"010","name":"Name 10"},
		{"code":"001","name":"Name 1"},         
		{"code":"002","name":"Name 2"},         
		{"code":"003","name":"Name 3"},         
		{"code":"004","name":"Name 4"},         
		{"code":"005","name":"Name 5"},         
		{"code":"006","name":"Name 6"},          
		{"code":"007","name":"Name 7"},          
		{"code":"008","name":"Name 8"},          
		{"code":"009","name":"Name 9"},          
		{"code":"010","name":"Name 10"},
		{"code":"001","name":"Name 1"},         
		{"code":"002","name":"Name 2"},         
		{"code":"003","name":"Name 3"},         
		{"code":"004","name":"Name 4"},         
		{"code":"005","name":"Name 5"},         
		{"code":"006","name":"Name 6"},          
		{"code":"007","name":"Name 7"},          
		{"code":"008","name":"Name 8"},          
		{"code":"009","name":"Name 9"},          
		{"code":"010","name":"Name 10"}, 
		{"code":"001","name":"Name 1"},         
		{"code":"002","name":"Name 2"},         
		{"code":"003","name":"Name 3"},         
		{"code":"004","name":"Name 4"},         
		{"code":"005","name":"Name 5"},         
		{"code":"006","name":"Name 6"},          
		{"code":"007","name":"Name 7"},          
		{"code":"008","name":"Name 8"},          
		{"code":"009","name":"Name 9"},          
		{"code":"010","name":"Name 10"}  
	]                                                          
}                                                           
